Resources:
    rdsDBInstance:
      Type: AWS::RDS::DBInstance
      Properties:
        AllocatedStorage: 5
        DBInstanceClass: db.t2.micro 
        DBName: wordpress
        DBSubnetGroupName: default
        Engine: mysql 
        MasterUsername: wordpress
        MasterUserPassword: w0rdpr355