Parameters:
  EnvironmentSize:
    Type: String
    AllowedValues:
      - Small
      - Medium
      - Large
    Default: Small
  ImageType:
    Type: String
    AllowedValues:
      - "AMA"
      - "Ubuntu"
    Default: "Ubuntu"
Mappings:
  InstanceType:
    Small:
      "DB": "db.t2.micro"
      "EC2": "t2.micro"
    Medium:
      "DB": "db.t2.small"
      "EC2": "t2.small"
    Large:
      "DB": "db.t2.medium"
      "EC2": "t2.medium"
  AMI:
    ap-southeast-2:
      "AMA": 
      "Ubuntu": 

Resources:
    rdsDBInstance:
      Type: AWS::RDS::DBInstance
      Properties:
        AllocatedStorage: 5
        StorageType: gp2
        DBInstanceClass: db.t2.micro 
        DBName: wordpress
        Engine: mysql 
        MasterUsername: wordpress
        MasterUserPassword: w0rdpr355
    myEC2Instance:
      Type: AWS::EC2::Instance
      Properties:
        ImageId: !FindInMap [AMI, AWS::Region, !Ref ImageType]
        InstanceType: !FindInMap [InstanceType, !Ref EnvironmentSize, EC2]
    s3Bucket:
      Type: AWS::S3::Bucket